# Generated by Django 5.2.7 on 2025-11-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siteuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=100, unique=True, verbose_name='Password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=0, verbose_name='Gender')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='Modify Time')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='Last Login Time')),
            ],
            options={
                'verbose_name': 'Site User',
                'verbose_name_plural': 'Site Users',
                'db_table': 'siteuser',
            },
        ),
    ]
