# Generated by Django 5.2.7 on 2025-11-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Password'),
        ),
    ]
